### ISSUE TITLE
Error when running `pip install -e`

### ISSUE THREAD

**Issue by hg0428** [Zyphra/transformers_zamba2#3]
### System Info

Platform: M3 Max
OS: MacOS Sequoia

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Clone the repo, cd into it, and run `pip install -e`. You will get the following error:
```
transformers_zamba2 % pip install -e .
Obtaining file:///Users/hudsongouge/Projects/transformers_zamba2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (0.25.1)
Requirement already satisfied: numpy<2.0,>=1.17 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (2024.9.11)
Requirement already satisfied: requests in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (2.32.3)
Collecting tokenizers<0.20,>=0.19 (from transformers==4.43.0.dev0)
  Downloading tokenizers-0.19.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /Users/hudsongouge/miniforge3/lib/python3.12/site-packages (from transformers==4.43.0.dev0) (4.66.5)
Collecting mamba-ssm==2.1.0 (from transformers==4.43.0.dev0)
  Downloading mamba_ssm-2.1.0.tar.gz (84 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      /private/var/folders/mm/3p04lc0x4fsdqhnkk_3j68v80000gn/T/pip-install-k8h04_45/mamba-ssm_6b6f7828754643a9ac9ec197632913a7/setup.py:119: UserWarning: mamba_ssm was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mm/3p04lc0x4fsdqhnkk_3j68v80000gn/T/pip-install-k8h04_45/mamba-ssm_6b6f7828754643a9ac9ec197632913a7/setup.py", line 189, in <module>
          if bare_metal_version >= Version("11.8"):
             ^^^^^^^^^^^^^^^^^^
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.2.2
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Expected behavior

It should not throw an error.

**Comment by hg0428** [comment]
As you can see, this is because I don't have an Nvidia GPU. I use Apple Silicon.

**Comment by DsnTgr** [comment]
After installed with `pip install -e .`, ModuleNotFoundError: No module named 'transformers' happens when I use `import transformers` . 

I tried it on Colab T4 and Kaggle P100.
